title: FlexxLink
description: Documentation for FlexxLink
theme: just-the-docs

url: https://soluluke.github.io/docutest

color_scheme: soluvine

aux_links:
  Template Repository: https://github.com/soluluke/docutest
